name: LEIHS/v5/zhdk-sync
windows:
  2:
    name: app
    command: |
      lein do clean, repl
  3: 
    name: deploy
    command: | 
      # ansible-playbook -v deploy/deploy_play.yml -i ../zhdk-inventory/prod-hosts-v5 -e 'prtg_url={{prod_v5_sync_prtg_url}}' -e 'leihs_api_token={{prod_v5_api_sync_token}}' --ssh-common-args '-o ProxyCommand="ssh -W %h:%p -q root@ci.zhdk.ch"'

  5:
    name: psql
    command: |
      psql -d leihs
  8:
    name: log
    command: |
      mkdir -p log && echo " " > log/debug.log && tail -f log/debug.log
